# -*- coding: utf-8 -*-
"""Multi Agent Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1juVRmbp70kpOMp41gtdSWDKi04DAxcw6
"""

!pip install -q crewai crewai-tools langchain-groq langchain-google-genai google-generativeai pillow

import os
import nest_asyncio
from google.colab import userdata
from getpass import getpass

nest_asyncio.apply()
print("Please enter your API Keys (press Enter after pasting each):")

os.environ["GOOGLE_API_KEY"] = getpass("Enter Google Gemini API Key: ")
os.environ["GROQ_API_KEY"] = getpass("Enter Groq API Key: ")
os.environ["TAVILY_API_KEY"] = getpass("Enter Tavily API Key: ")

print("\nKeys successfully set!")

from crewai.tools import BaseTool
import google.generativeai as genai
from PIL import Image
import os

class ImageToCodeTool(BaseTool):
    name: str = "Image Code Extractor"
    description: str = "Takes an image file path, reads the image, and extracts code and error messages."

    def _run(self, file_path: str) -> str:
        try:
            # Configure Gemini
            genai.configure(api_key=os.environ["GOOGLE_API_KEY"])
            model = genai.GenerativeModel('gemini-pro')

            # Load Image
            img = Image.open(file_path)

            # Prompt the Vision Model
            prompt = "Extract the code snippet and the exact error message present in this image. Return only the code and the error text."
            response = model.generate_content([prompt, img])

            return response.text
        except Exception as e:
            return f"Error processing image: {str(e)}"

print("Custom Vision Tool created successfully.")

!pip install tavily-python

!pip install litellm

import os
from crewai import Agent, Task, Crew, Process, LLM
from crewai.tools import BaseTool
from tavily import TavilyClient

class CustomSearchTool(BaseTool):
    name: str = "Internet Search Tool"
    description: str = "Search the web for technical solutions using Tavily."

    def _run(self, query: str) -> str:
        try:
            tavily_client = TavilyClient(api_key=os.environ["TAVILY_API_KEY"])
            response = tavily_client.search(query=query)
            results = []
            if 'results' in response:
                for res in response['results'][:3]:
                    results.append(f"Source: {res['title']}\nContent: {res['content']}\n")
            return "\n".join(results)
        except Exception as e:
            return f"Error performing search: {str(e)}"

groq_llm = LLM(
    model="groq/llama-3.3-70b-versatile",
    api_key=os.environ["GROQ_API_KEY"]
)

# 3. Initialize Tools
vision_tool = ImageToCodeTool()
search_tool = CustomSearchTool()

# 4. Define Agents

extractor = Agent(
    role='Code Extractor',
    goal='Extract code and error text from image files.',
    backstory='You are an optical character recognition expert specialized in programming screenshots.',
    tools=[vision_tool],
    llm=groq_llm,
    verbose=True
)

researcher = Agent(
    role='StackOverflow Researcher',
    goal='Find the correct solution for the extracted error.',
    backstory='You are an expert at searching technical documentation and forums to find bug fixes.',
    tools=[search_tool],
    llm=groq_llm,
    verbose=True
)

fixer = Agent(
    role='Senior Developer',
    goal='Write the corrected code and explain the fix.',
    backstory='You provide safe, clean, and commented code fixes based on research.',
    llm=groq_llm,
    verbose=True
)

# 5. Define Tasks

task_extract = Task(
    description='Use the "Image Code Extractor" tool to analyze the image at path: "{image_path}". Extract the code and the error message.',
    expected_output='Text containing the Code Snippet and Error Message.',
    agent=extractor
)

task_search = Task(
    description='Take the extracted error and code from the previous task. Search the web for a solution to this specific error.',
    expected_output='A summary of the solution found.',
    agent=researcher
)

task_fix = Task(
    description='Based on the research, provide the CORRECTED code. Explain step-by-step how to apply the fix.',
    expected_output='1. The Corrected Code Block\n2. Explanation of the solution.',
    agent=fixer
)

# 6. Assemble Crew
crew = Crew(
    agents=[extractor, researcher, fixer],
    tasks=[task_extract, task_search, task_fix],
    process=Process.sequential,
    verbose=True
)

print("Crew assembled successfully with Groq Native LLM.")

from google.colab import files

print("Please upload your screenshot containing the code/error:")
uploaded = files.upload()

if uploaded:
    image_filename = list(uploaded.keys())[0]
    print(f"\nProcessing image: {image_filename}...\n")

    result = crew.kickoff(inputs={'image_path': image_filename})

    from IPython.display import Markdown
    display(Markdown("## 🛠️ **Final Code Fix**"))
    display(Markdown(str(result)))
else:
    print("No file uploaded.")















